
import React, { useState, useEffect } from 'react';
import { generateCheatSheet } from '../services/gemini';
import { CheatSheetData } from '../types';
import { FileText, Printer, ArrowLeft, Loader2, Download, Copy } from 'lucide-react';

interface Props {
    topic: string;
    nodes: { label: string }[];
    onBack: () => void;
}

const CheatSheet: React.FC<Props> = ({ topic, nodes, onBack }) => {
    const [data, setData] = useState<CheatSheetData | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetch = async () => {
            setLoading(true);
            const res = await generateCheatSheet(topic, nodes);
            setData(res);
            setLoading(false);
        }
        fetch();
    }, [topic]);

    const handleExportMarkdown = () => {
        if (!data) return;
        
        let md = `# ${topic} - InLayman Master Guide\n\n`;
        md += `> Generated by InLayman AI\n\n`;
        
        data.nodes.forEach((node, i) => {
            md += `## ${i+1}. ${node.concept}\n`;
            md += `**Analogy:** _"${node.analogy}"_\n\n`;
            md += `**Technical Term:** \`${node.keyTerm}\`\n\n`;
            md += `---\n\n`;
        });
        
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${topic.replace(/\s+/g, '_')}_CheatSheet.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    };

    if (loading) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin text-primary-500 w-10 h-10"/></div>;

    if (!data) return <div>Failed to generate cheat sheet.</div>;

    return (
        <div className="max-w-4xl mx-auto p-8 min-h-screen print:p-0">
            <div className="flex justify-between items-center mb-8 print:hidden">
                <button onClick={onBack} className="text-slate-400 hover:text-white flex items-center gap-2"><ArrowLeft size={16}/> Back</button>
                <div className="flex gap-2">
                    <button onClick={handleExportMarkdown} className="bg-slate-800 text-slate-200 hover:text-white hover:bg-slate-700 px-4 py-2 rounded-lg flex items-center gap-2 border border-slate-700 transition-colors">
                        <Download size={16}/> Export Markdown
                    </button>
                    <button onClick={() => window.print()} className="bg-primary-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-primary-500 transition-colors shadow-lg shadow-primary-900/20">
                        <Printer size={16}/> Print PDF
                    </button>
                </div>
            </div>

            <div className="bg-white text-slate-900 p-12 shadow-2xl rounded-xl print:shadow-none relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-primary-100 rounded-bl-full opacity-50"></div>
                
                <div className="border-b-4 border-slate-900 pb-6 mb-8 flex justify-between items-end relative z-10">
                    <div>
                        <h1 className="text-4xl font-black uppercase tracking-tighter text-slate-900">{topic}</h1>
                        <p className="text-slate-500 font-medium">InLayman One-Page Master Guide</p>
                    </div>
                    <div className="text-right">
                        <div className="text-xs font-bold text-slate-400 uppercase">Generated By</div>
                        <div className="font-bold text-primary-600">InLayman AI</div>
                    </div>
                </div>

                <div className="space-y-6 relative z-10">
                    {data.nodes.map((node, i) => (
                        <div key={i} className="flex gap-6 p-4 bg-slate-50 rounded-lg border border-slate-200 break-inside-avoid hover:border-primary-200 transition-colors">
                            <div className="w-12 h-12 bg-slate-900 text-white flex items-center justify-center rounded-full font-bold text-xl shrink-0 shadow-lg">
                                {i+1}
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-slate-900 mb-1">{node.concept}</h3>
                                <div className="text-primary-700 italic font-medium mb-2 border-l-2 border-primary-500 pl-3">
                                    "{node.analogy}"
                                </div>
                                <div className="text-sm text-slate-600">
                                    <span className="font-bold uppercase text-xs text-slate-400 tracking-wider">Tech Term: </span> 
                                    <span className="font-mono bg-slate-200 px-1 py-0.5 rounded text-slate-800">{node.keyTerm}</span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-12 pt-6 border-t border-slate-200 text-center text-slate-400 text-xs uppercase tracking-widest">
                    Mastery achieved through Analogy-First Learning
                </div>
            </div>
        </div>
    );
}

export default CheatSheet;
